### ISSUE TITLE
Handling Api request with useFetch 

### ISSUE THREAD

**Issue by AyanUpadhaya** [sayshark75/code-bank#2]
**Description:** Sometimes we may need to handle API request for getting data or posting. May be we aren't using Rtk query or any other package like Axios but we simply want a reusable piece of code that we can use for API request. We can create a custom hook call useFetch in React that can do this for us. Like often we may need to write headers or add authorization token from localeStorage or we may need to add data for posting and also handling errors in async functions, in these type of case a reusable hook can be very helpful. So here is my code snippet

```
const useFetch = () => {
  const fetchData = async (url, options = {}) => {
    const { authToken = "", customErrorHandler = null } = options;

    const res = await fetch(url, {
      method: "GET",
      headers: {
        Authorization: `Bearer ${authToken}`,
      },
    });

    if (!res.ok) {
      if (customErrorHandler) {
        customErrorHandler(res);
      } else {
        throw new Error(`Error fetching data from ${url}`);
      }
    }

    return res.json();
  };

  const postData = async (url, data, options = {}) => {
    const { authToken = "", type, customErrorHandler = null } = options;

    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${authToken}`,
      },
      body: JSON.stringify(data),
    });

    if (!res.ok) {
      if (customErrorHandler) {
        customErrorHandler(res);
      } else {
        throw new Error(`Error posting data to ${url}`);
      }
    }

    return res.json();
  };

  return { fetchData, postData };
};

export default useFetch;

```
### Practical Use Case

A practical use case could be like this where we want to handle login request with login credentials, store authentication data in redux also handle errors with custom error handler function

```
  const { setAuth, dispatch } = useStoreAuth();
  const { postData } = useFetch();
  const navigate = useNavigate();
  const [isLoading, setIsLoading] = useState(false);

  const handleLogin = async (event) => {
    event.preventDefault();
    setIsLoading(true);
    const form = event.target;
    const username = form.username.value;
    const password = form.password.value;

    const data = {
      username: username,
      password: password,
    };

    const handleCustomError = (res) => {
      if (res.status === 401) {
        throw new Error("Invalid email or password");
      } else if (res.status === 404) {
        throw new Error("User not found");
      } else {
        throw new Error("Login failed");
      }
    };

    try {
      const response = await postData(loginRoute, data, {
        type: "login",
        customErrorHandler: handleCustomError,
      });

      if (response) {
        infoNotify("Logged in successfully");
        dispatch(setAuth(response));
        setIsLoading(false);
        navigate("/");
      }
    } catch (error) {
      console.log(error.message);
      setIsLoading(false);
    }
  };

```

We can also add additional functions for handling update and delete request. In this way I think we can make our code cleaner and reusable. Thank you.

**Comment by sayshark75** [comment]
Hi,
- We Reviewed your code,
- The useFetch Hook, is performing the same task as a fetch API, 
- Just encapsulated in the useFetch Hook.
- Thank you for your response, but we require a more robust approach.
- We are working on it, and when it done, we authorize your name with that soon.
- If you have a new code snippet idea, please share again 😄

**Comment by AyanUpadhaya** [comment]
> Hi,
> 
> * We Reviewed your code,
> * The useFetch Hook, is performing the same task as a fetch API,
> * Just encapsulated in the useFetch Hook.
> * Thank you for your response, but we require a more robust approach.
> * We are working on it, and when it done, we authorize your name with that soon.
> * If you have a new code snippet idea, please share again 😄

Thank you for your response. Sure if something new comes up I'll definitely share with the community....
